name: Autobahn test
on: [push]
jobs:
    build:
        name: Autobahn integrations tests
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
        ## Following are for running locally with https://github.com/nektos/act
        #   - name: Down autobahn services
        #     run: docker-compose -f ${{github.workspace}}/tests/autobahn/docker-compose.yml down
        #   - name: Build autobahn services
        #     run: docker-compose -f ${{github.workspace}}/tests/autobahn/docker-compose.yml build
          - name: Run autobahn services
            run: docker-compose -f ${{github.workspace}}/tests/autobahn/docker-compose.yml up -d
          - name: Build client test
            run: docker exec autobahn_client "v" "/src/tests/autobahn/autobahn_client.v" 
          - name: Run client test
            run: docker exec autobahn_client "/src/tests/autobahn/autobahn_client"  
          - name: Run server test
            run: docker exec autobahn_server "wstest" "-m" "fuzzingclient" "-s" "/config/fuzzingclient.json" 
          - name: Copy reports
            run: docker cp autobahn_server:/config ${{github.workspace}}/config
          - name: Publish report 
            uses: actions/upload-artifact@v2
            with:
                name: reports
                path: ${{github.workspace}}/config
